language: java
#jdk: oraclejdk8
dist: xenial
python:
  - "3.6"
os: linux

#addons:
#  apt:
#    sources:
#      - deadsnakes # source required so it finds the package definition below
#    packages:
#      - python3.6

cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.m2

services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.6
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project gifted-cooler-293414
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials my-first-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./mvnw clean install -B
  - docker build -t mrdocker007/test -f Dockerfile .

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master