print('=============== INSERT QUOTES ===============');
print('Current number of items in collection (quote): ' + db.quote.count());

db.quote.insertOne( { quoteLine: "Dans la vie on ne fait pas ce que l'on veut mais on est responsable de ce que l'on est.", author: "Jean-Paul Sartre" } )
db.quote.insertOne( { quoteLine: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" } )
db.quote.insertOne( { quoteLine: "On passe une moitié de sa vie à attendre ceux qu'on aimera et l'autre moitié à quitter ceux qu'on aime.", author: "Victor Hugo" } )
db.quote.insertOne( { quoteLine: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Exige beaucoup de toi-même et attends peu des autres. Ainsi beaucoup d'ennuis te seront épargnés.", author: "Confucius" } )
db.quote.insertOne( { quoteLine: "Le monde est dangereux à vivre ! Non pas tant à cause de ceux qui font le mal, mais à cause de ceux qui regardent et laissent faire.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Il n'existe que deux choses infinies, l'univers et la bêtise humaine... mais pour l'univers, je n'ai pas de certitude absolue.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "La nature fait les hommes semblables, la vie les rend différents.", author: "Confucius" } )
db.quote.insertOne( { quoteLine: "Le monde est dangereux à vivre ! Non pas tant à cause de ceux qui font le mal, mais à cause de ceux qui regardent et laissent faire.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Choisissez un travail que vous aimez et vous n'aurez pas à travailler un seul jour de votre vie.", author: "Confucius" } )
db.quote.insertOne( { quoteLine: "Placez votre main sur un poêle une minute et ça vous semble durer une heure. Asseyez vous auprès d'une jolie fille une heure et ça vous semble durer une minute. C'est ça la relativité.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "La valeur d'un homme tient dans sa capacité à donner et non dans sa capacité à recevoir.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "N'essayez pas de devenir un homme qui a du succès. Essayez de devenir un homme qui a de la valeur.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Le monde ne sera pas détruit par ceux qui font le mal, mais par ceux qui les regardent sans rien faire.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Soit A un succès dans la vie. Alors A = x + y + z, où x = travailler, y = s'amuser, z = se taire.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Je ne sais pas comment sera la troisième guerre mondiale, mais je sais qu'il n'y aura plus beaucoup de monde pour voir la quatrième.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "La théorie, c'est quand on sait tout et que rien ne fonctionne. La pratique, c'est quand tout fonctionne et que personne ne sait pourquoi. Ici, nous avons réuni théorie et pratique : Rien ne fonctionne... et personne ne sait pourquoi !", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Le mot progrès n'aura aucun sens tant qu'il y aura des enfants malheureux.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "La folie, c'est se comporter de la même manière et s'attendre à un résultat différent.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Le hasard, c'est Dieu qui se promène incognito.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "L'imagination est plus importante que le savoir.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Il est hélas devenu évident aujourd'hui que notre technologie a dépassé notre humanité.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Une personne qui n'a jamais commis d'erreurs n'a jamais tenté d'innover.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "L'école devrait toujours avoir pour but de donner à ses élèves une personnalité harmonieuse, et non de les former en spécialiste.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Il n'y a que deux façons de vivre sa vie : l'une en faisant comme si rien n'était un miracle, l'autre en faisant comme si tout était un miracle.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Les grands esprits ont toujours rencontré une opposition farouche des esprits médiocres.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Un problème créé ne peut être résolu en réfléchissant de la même manière qu'il a été créé.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Il est plus facile de désintégrer un atome qu'un préjugé.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Ne t'inquiète pas si tu as des difficultés en maths, je peux t'assurer que les miennes sont bien plus importantes !", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Le progrès technique est comme une hache qu'on aurait mis dans les mains d'un psychopathe.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Ce qui compte ne peut pas toujours être compté, et ce qui peut être compté ne compte pas forcément.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Un problème sans solution est un problème mal posé.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "L'enseignement devrait être ainsi : celui qui le reçoit le recueille comme un don inestimable mais jamais comme une contrainte pénible.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "La valeur morale ne peut pas être remplacée par la valeur intelligence et j'ajouterai : Dieu merci !", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Ce qui fait la vraie valeur d'un être humain, c'est de s'être délivré de son petit moi.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Nous aurons le destin que nous aurons mérité.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Si vous ne pouvez expliquer un concept à un enfant de six ans, c'est que vous ne le comprenez pas complètement.", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Ce n'est pas à cause de l'attraction terrestre que des gens tombent... amoureux !", author: "Albert Einstein" } )
db.quote.insertOne( { quoteLine: "Celui qui sait obéir saura ensuite commander.", author: "Confucius" } )
db.quote.insertOne( { quoteLine: "La nature fait les hommes semblables, la vie les rend différents.", author: "Confucius" } )
db.quote.insertOne( { quoteLine: "L'expérience prouve que celui qui n'a jamais confiance en personne ne sera jamais déçu.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Qui ne doute pas acquiert peu.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Dans la nature, tout a toujours une raison. Si tu comprends cette raison, tu n'as plus besoin de l'expérience. ", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Tout obstacle renforce la détermination. Celui qui s'est fixé un but n'en change pas.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Le jour viendra où les personnes comme moi regarderont le meurtre des animaux comme ils regardent aujourd'hui le meurtre des êtres humains.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Comme une journée bien remplie nous donne un bon sommeil, une vie bien vécue nous mène à une mort paisible.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Jamais le soleil ne voit l'ombre.", author: "Léonard de Vinci" } )
db.quote.insertOne( { quoteLine: "Les détails font la perfection, et la perfection n'est pas un détail.", author: "Léonard de Vinci" } )

print('Number of items in collection (quote): ' + db.quote.count());